// ============================================
// Sales Analytics - DAX Query Script
// ============================================
// 
// HOW TO USE THIS SCRIPT:
// 1. Open Power BI Desktop with your semantic model
// 2. Go to DAX Query View (icon on left side)
// 3. Create a new query tab
// 4. Copy and paste this entire script
// 5. Click "Run" to test the measures
// 6. Click "Update model with changes" to add all measures to your model
//    OR use the CodeLens "Add new measure" links above each DEFINE MEASURE
//
// NOTE: The _Measures table must exist in your model before running this.
// If it doesn't exist, create it first with: _Measures = ROW("Placeholder", 1)
// ============================================

// --------------------------------------------
// REVENUE MEASURES
// --------------------------------------------

DEFINE
    MEASURE '_Measures'[Total Revenue] = 
        SUM(Sales[TotalAmount])

    MEASURE '_Measures'[Total Discount] = 
        SUMX(Sales, Sales[Discount] * Sales[Quantity])

    MEASURE '_Measures'[Gross Revenue] = 
        SUMX(Sales, Sales[UnitPrice] * Sales[Quantity])

    MEASURE '_Measures'[Avg Transaction Value] = 
        DIVIDE([Total Revenue], [Total Transactions])

// --------------------------------------------
// COST & MARGIN MEASURES
// --------------------------------------------

    MEASURE '_Measures'[Total Cost] = 
        SUM(Sales[TotalCost])

    MEASURE '_Measures'[Gross Profit] = 
        [Total Revenue] - [Total Cost]

    MEASURE '_Measures'[Gross Margin %] = 
        DIVIDE([Gross Profit], [Total Revenue])

// --------------------------------------------
// QUANTITY MEASURES
// --------------------------------------------

    MEASURE '_Measures'[Total Quantity] = 
        SUM(Sales[Quantity])

    MEASURE '_Measures'[Total Transactions] = 
        COUNTROWS(Sales)

    MEASURE '_Measures'[Avg Units per Transaction] = 
        DIVIDE([Total Quantity], [Total Transactions])

// --------------------------------------------
// TIME INTELLIGENCE MEASURES
// --------------------------------------------

    MEASURE '_Measures'[Revenue YTD] = 
        TOTALYTD([Total Revenue], Calendar[Date])

    MEASURE '_Measures'[Revenue MTD] = 
        TOTALMTD([Total Revenue], Calendar[Date])

    MEASURE '_Measures'[Revenue PY] = 
        CALCULATE([Total Revenue], SAMEPERIODLASTYEAR(Calendar[Date]))

    MEASURE '_Measures'[Revenue YoY %] = 
        VAR CurrentPeriod = [Total Revenue]
        VAR PriorPeriod = [Revenue PY]
        RETURN
            DIVIDE(CurrentPeriod - PriorPeriod, PriorPeriod)

    MEASURE '_Measures'[Revenue vs PY] = 
        [Total Revenue] - [Revenue PY]

// --------------------------------------------
// TARGET MEASURES
// --------------------------------------------

    MEASURE '_Measures'[Revenue Target] = 
        SUM(Targets[RevenueTarget])

    MEASURE '_Measures'[Revenue vs Target] = 
        [Total Revenue] - [Revenue Target]

    MEASURE '_Measures'[Revenue vs Target %] = 
        DIVIDE([Total Revenue] - [Revenue Target], [Revenue Target])

    MEASURE '_Measures'[% of Target] = 
        DIVIDE([Total Revenue], [Revenue Target])

// --------------------------------------------
// EVALUATE - Test the measures
// --------------------------------------------

EVALUATE
SUMMARIZECOLUMNS(
    Calendar[Year],
    "Total Revenue", [Total Revenue],
    "Total Cost", [Total Cost],
    "Gross Margin %", [Gross Margin %],
    "Transactions", [Total Transactions]
)
ORDER BY Calendar[Year]
